---
title: "Let's make a presentation with Quarto"
author: "David Schoch"
lesson: 5
institute: GESIS
date: "2023-06-20"
date-format: "YYYY-MM-DD"
footer: "[Automated Reports & Co with Quarto and Markdown](https://gesiscss.github.io/quarto-workshop/)"
format: fakegesis-revealjs
---

## Quarto presentation formats


- `revealjs` essentially the replacement for `xaringan`

- `beamer` for LaTex slides

- Powerpoint for when you have no choice...

## What is revealjs?

> reveal.js is an open source HTML presentation framework. It’s a tool that enables anyone with a web browser to create fully-featured and beautiful presentations for free.

. . .

There is an R package for RMarkdown 
```r
install.packages("revealjs")
```
but it is rarely used since `xaringan` is more popular


## No need to learn new syntax


```{.markdown  code-line-numbers="false"}
---
format: revealjs
---

## Slide 1
Add some content

## Slide 2
- and 
- maybe
- a 
- list

```

Render to pptx? set `format: pptx`  
Render to beamer? set `format: beamer`

:::{.aside}
Switching between formats is THAT easy as long as you do not have any "fancy" features included
:::

## HTML divs and spans with Pandoc

```{.markdown  code-line-numbers="false"}
::: {.class}
Content in a div with a class
:::

Some text with a specific [span]{.span-class}
```

Pandoc translates this to
```{.html code-line-numbers="false"}
<div class="class">
   Content in a div with a class
</div>
Some text with a specific <span class="span-class">span</span>
```

## Incremental lists

```{.markdown code-line-numbers="false"}
:::{.incremental}
- item 1
- item 2
- item 3
:::
```

:::{.incremental}
- item 1
- item 2
- item 3
:::

## Incremental Slides

Use `. . .` syntax  

```{.markdown code-line-numbers="false"}
This appears first 

. . .

This second
```

. . .

This appears first 

. . .

This second

## Fragments, Basics

```{.markdown code-line-numbers="false"}

::: {.fragment}
Fade in
:::

::: {.fragment .fade-out}
Fade out
:::

::: {.fragment .highlight-red}
Highlight red
:::

::: {.fragment .fade-in-then-out}
Fade in, then out
:::

::: {.fragment .fade-up}
Slide up while fading in
:::
```

## Fragments, Basics

::: {.fragment}
Fade in
:::

::: {.fragment .fade-out}
Fade out
:::

::: {.fragment .highlight-red}
Highlight red
:::

::: {.fragment .fade-in-then-out}
Fade in, then out
:::

::: {.fragment .fade-up}
Slide up while fading in
:::

## Fragments, More

This is an [important sentence!]{.fragment .highlight-red}
```{.markdown code-line-numbers="false"}
This is an [important sentence!]{.fragment .highlight-red}
```

::: {.fragment .fade-in}
::: {.fragment .highlight-red}
::: {.fragment .semi-fade-out}
Fade in > Turn red > Semi fade out
:::
:::
:::

. . .

```{.markdown code-line-numbers="false"}
::: {.fragment .fade-in}
::: {.fragment .highlight-red}
::: {.fragment .semi-fade-out}
Fade in > Turn red > Semi fade out
:::
:::
:::
```

## Multiple Columns

```{.markdown code-line-numbers="false"}
:::: {.columns}

::: {.column width="40%"}
Left column
:::

::: {.column width="60%"}
Right column
:::

::::
```

:::: {.columns}

::: {.column width="40%"}
Left column
:::

::: {.column width="60%"}
Right column
:::

::::